apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-ed
  template:
    metadata:
      labels:
        app: backend-ed
    spec:
      containers:
        - name: backend-ed
          image: swarnadeep85/backend-ed:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: SESSION_SECRET
            - name: NODE_ENV
              value: "development"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: JWT_SECRET
            - name: JWT_SECRET_REFRESH
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: JWT_SECRET_REFRESH
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: GOOGLE_CLIENT_ID
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: SMTP_PASS
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: backend-ed-secret
                  key: SMTP_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ed-service
spec:
  selector:
    app: backend-ed
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30003
  type: NodePort
