apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
data:
  PORT: "5000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  NODE_ENV: "development"
  GOOGLE_CLIENT_ID: "518509794849-196l9q6l5hslle5n3soit76edpms744p.apps.googleusercontent.com"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
