apiVersion: v1
kind: Secret
metadata:
  name: user-management-secret
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYitzcnY6Ly9kZWJzd2FybmFkZWVwODU6RGRRRFJmMHkxTWNjUWpvekBjbHVzdGVyMC5mbjVkZi5tb25nb2RiLm5ldC9IUi1Vc2VyLU1hbmFnZW1lbnQtZGI/cmV0cnlXcml0ZXM9dHJ1ZSZhcHBOYW1lPUNsdXN0ZXIw
  MONGO_URI: bW9uZ29kYitzcnY6Ly9kZWJzd2FybmFkZWVwODU6RGRRRFJmMHkxTWNjUWpvekBjbHVzdGVyMC5mbjVkZi5tb25nb2RiLm5ldC9IUi1Vc2VyLU1hbmFnZW1lbnQtZGI/cmV0cnlXcml0ZXM9dHJ1ZSZhcHBOYW1lPUNsdXN0ZXIw
  SESSION_SECRET: YjdhZWQ2ZTNiMzY4NGZkMWZjMjMzMDBjNWI5YTQ1ODY5NTA4OTE4MTk4ODhlNmJjMTZmZjVkYjExYmI2ZTY5ZQ==
  JWT_SECRET: NjliOTAyYzMwNzNhNDBlY2I0YjU3NDVkNWU5OTJiM2NjYWM2OWJhZWY4ZTZmMTJlOTJhYzA0ODM4YzhhMWEzMw==
  JWT_SECRET_REFRESH: OTdlZmQzZjBlYmIwYThhNjZkOGE2OTE2ODcwOTE4ZWY2NGZmYzVmNGIyYjkzNzEyNzMyZTRiYmZlMDk4NmYwZg==
  SMTP_USER: c3dhcm5hZGVlcGRlYmRldmVsb3BtZW50QGdtYWlsLmNvbQ==
  SMTP_PASS: cGZhY3F5ZWJwbnh2cW1jcA==
